---
# tasks file for preamble
- name: Check connection
  ping:
  ignore_errors: yes
  ignore_unreachable: yes
  register: ping

- name: Set connection status
  set_fact:
    reachable: "{{ 'success' in ping }}"
    preamble_username: "{{ ansible_user }}"

- name: Set username
  set_fact:
    preamble_user: "{{ ansible_user }}"
  when: reachable

- name: Setup service user
  vars:
    ansible_user: "{{ preamble_user }}"
  block:
  - name: "Create user {{ preamble_username }}"
    user:
      name: "{{ preamble_username }}"
      system: yes
      shell: /bin/nologin
      password_lock: yes
    register: user