---
- name: Check Connection
  ping:
  ignore_errors: yes
  ignore_unreachable: yes
  register: ping

- name: Set connection status
  set_fact:
    reachable: "{{ 'success' in ping }}"
    preamble_unreachable_user: "{{ ansible_user }}"

- name: Set user
  set_fact:
    preamble_user: "{{ ansible_user }}"
  when: reachable

- name: Setup service user
  vars:
    ansible_user: "{{ preamble_user }}"
  block:
  - name: Gather Facts
    setup:

  - name: Setup service user
    include_tasks: user.yml

  - name: Setup ssh access to user
    include_tasks: ssh.yml
    when: ansible_connection in preamble_ssh_connection_types