---
- name: Checking connection
  ping:
  ignore_errors: yes
  ignore_unreachable: yes
  register: ping

- name: Setting connection status
  set_fact:
    reachable: "{{ 'unreachable' not in ping }}"
    preamble_ansible_user: "{{ ansible_user }}"

# When default user is available, we should use it.
- name: Setting user
  set_fact:
    preamble_user: "{{ ansible_user }}"
  when: reachable

- name: Setting up service user
  become: yes
  vars:
    ansible_user: "{{ preamble_user }}"
  block:
  - name: Gathering Facts
    setup:

  - name: Setting up service user
    include_tasks: user.yml

  - name: Setting up SSH access to user
    include_tasks: ssh.yml
    when: ansible_connection in preamble_ssh_connection_types