---
# tasks file for preamble
- name: Check Connection
  ping:
  ignore_errors: yes
  ignore_unreachable: yes
  register: ping

- name: Set connection status
  set_fact:
    reachable: "{{ 'success' in ping }}"
    preamble_username: "{{ ansible_user }}"

- name: Set username
  set_fact:
    preamble_user: "{{ ansible_user }}"
  when: reachable

- name: Setup service user
  vars:
    ansible_user: "{{ preamble_user }}"
  block:
  - name: "Create user {{ preamble_username }}"
    user:
      name: "{{ preamble_username }}"
      system: yes
      shell: /bin/nologin
      password_lock: yes
      comment: Ansible Management User
    register: user

  - name: "Add user {{ preamble }} to sudo"
    lineinfile:
      path: /etc/sudoers.d/ansible
      line: 'ansible ALL=(ALL) NOPASSWD: ALL'
      state: present
      mode: 0440
      create: yes
      validate: "/usr/sbin/visudo -cf %s"
  
  - name: Set includedir in sudoers
    lineinfile:
      dest: /etc/sudoers
      line: "#includedir /etc/sudoers.d"
      state: present
      validate: "/usr/sbin/visudo -cf %s"