---
- name: Creating ssh key for hosts
  when: preamble_generate_ssh_key
  block:
  - name: Generating new key
    openssh_keypair:
      path: "~/.ssh/{{ preamble_ansible_user }}_rsa"
    register: keypair
    delegate_to: localhost
    run_once: yes
  - name: Add keypair
    set_fact:
      preamble_ssh_keys: "{{ preamble_ssh_keys + [keypair.public_key] }}"

- name: Adding ssh key
  authorized_key:
    user: "{{ preamble_ansible_user }}"
    state: present
    key: "{{ item }}"
  loop: "{{ preamble_ssh_keys }}"
