---
- name: "Creating user {{ preamble_ansible_user }}"
  user:
    name: "{{ preamble_ansible_user }}"
    system: yes
    shell: /bin/bash
    password_lock: yes
    comment: Ansible Management User
  register: user

- name: "Enabling sudo for user {{ preamble_ansible_user }}"
  blockinfile:
    path: /etc/sudoers.d/ansible
    block: |
      {{ preamble_ansible_user }} ALL=(ALL) NOPASSWD: ALL
    state: present
    mode: 0440
    create: yes
    validate: "/usr/sbin/visudo -cf %s"

- name: Including config in sudoers
  lineinfile:
    dest: /etc/sudoers
    line: "#includedir /etc/sudoers.d"
    state: present
    validate: "/usr/sbin/visudo -cf %s"
